apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-nodejs
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 676206915498.dkr.ecr.us-east-1.amazonaws.com/test-kuber:auth-service
        ports:
        - containerPort: 3000
