apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-nodejs
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 676206915498.dkr.ecr.us-east-1.amazonaws.com/test-kuber:user-service
        ports:
        - containerPort: 3000